### ISSUE TITLE
How to compile last version

### ISSUE THREAD

**Issue by DURANDRomain** [lubomyr/uae4arm#18]
Hi 

I want to compile the last version to see if it works on AndroidTV (the emulator starts, but it waits to insert a disk, same with all amiga configurations, with adf or whd).

Im starting to set up a compilation environnent with Debian 10 (Buster), and openjdk-8 is not available, im installing openjdk-11. Do I have a chance to compile ?

Any advice on how to make UAE4ARM work on AndroidTV (pie) ?

**Comment by lubomyr** [comment]
Hi,
Yes, can try to use any available openjdk

сб, 17 серп. 2019 о 13:40 DURANDRomain <notifications@github.com> пише:

**Comment by DURANDRomain** [comment]
Ok so I got:

```
Android NDK: ERROR:jni/../jni/charset/Android.mk:charset: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that jni/../jni/charset/lib/armeabi-v7a/libcharset.so exists  or that its path is correct
/root/Android/android-ndk-r17b/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

```

If I launch build.sh in ~/androidsdl/project/jni/charset/src I get:
```
checking whether the C compiler works... no
configure: error: in `/root/androidsdl/project/jni/charset/src/arm64-v8a/libiconv-1.15':
configure: error: C compiler cannot create executables
See `config.log' for more details
+ exit 1
```
Looking for libcharset.so:
```
root@androidCompilator:~/androidsdl# ls project/jni/charset/
Android.mk  src
root@androidCompilator:~/androidsdl# locate libcharset.so
```

Maybe UAE4ARM don't work on my android tv box (X96Max) because it is a 32bits android ? Is it possible ?

Anyway, do you have some idea ? Is there a place where I can find an APK with latest UEA4ARM ?
