### ISSUE TITLE
GUI Crash on "input target" drop down

### ISSUE THREAD

**Issue by thatman84** [lubomyr/uae4arm#19]
This crash happens when you try to scroll down beyond the last entry of the inputs list.

Recreated on Shield TV and Samsung S7

![UAE-Crash Report](https://user-images.githubusercontent.com/26202064/63723321-0b5a1200-c84d-11e9-9e6b-58dd69698471.PNG)

Any further details needed please ask

(Thansk for keeping this emulator going @lubomyr much apprechiated)

**Comment by lubomyr** [comment]
fixed
