### ISSUE TITLE
Cannot browse for files from external SD or USB

### ISSUE THREAD

**Issue by lovrenco** [lubomyr/uae4arm#3]
It only allows browsing to internal /storage/emulated/0/
I would like to store files on /storage/sdcard 

Is there any way to enable this?

**Comment by lubomyr** [comment]
try to find uae4arm root folder
it can be something like this
/storage/sdcard0/Android/data/atua.anddev.uae4arm/files/conf

try to manual edit path in adfdir.conf file which located in this directory

**Comment by lovrenco** [comment]
Thanks @lubomyr , it works after editing path in first line, now USB and External SD is available for selection. I just tried it so I cannot say if everything will work, but it is browsing folders as expected.

Wether to enable editing path from the app or not I leave that to developers, for me it is important that it can be tweaked this way, Thanks once again.
