### ISSUE TITLE
Access to only media files

### ISSUE THREAD

**Issue by hguzelis** [lubomyr/uae4arm#34]
I'm using Samsung S10 and Adroid 11. When i download program, asks only access to media files. I give access. But i can not change this type of access to "all storage files". When i try to load some ADF files to Disk drive, i see nothing. Please see attached picture. 
![Screenshot_20211119-194458_Uae4arm](https://user-images.githubusercontent.com/94702703/142660503-43b06050-6027-4e70-9f6f-0e7213cd6630.jpg)

**Comment by mike111769** [comment]
uaeconfig.uae

storage/emulated/0/Android/data/atua.anddev.uae4arm/files/conf

pandora.rom_path=/storage/emulated/0/Android/data/atua.anddev.uae4arm/files/kickstarts/
pandora.floppy_path=/storage/emulated/0/Android/data/atua.anddev.uae4arm/files/disks/
pandora.hardfile_path=/storage/emulated/0/Android/data/atua.anddev.uae4arm/files/
pandora.cd_path=/storage/emulated/0/Android/data/atua.anddev.uae4arm/files/cd32/

storage/emulated/0/Android/data/atua.anddev.uae4arm/files/conf

Mike

**Comment by hguzelis** [comment]
Thank you. I understand that i need to use those directories to run emulation and manage disks etc.
