### ISSUE TITLE
Can't install WorkBench

### ISSUE THREAD

**Issue by chiaravalle** [lubomyr/uae4arm#43]
Hello all.
I'm trying to install Workbench, but I'm stuck as the installation fails with an error (see 
![Screenshot_20230826-183224_Uae4arm](https://github.com/lubomyr/uae4arm/assets/71562926/9f18ddcd-667e-44d6-b135-7f1dfaac594f)
)
This happens as soon as I insert the Locale floppy.

Can you help?
Thanks if so.

**Comment by mike111769** [comment]
Try a different image file,it looks to me like that one is corrupted.

Mike

**Comment by chiaravalle** [comment]
I thought it too, I tried 3 floppy images from various sources: Archive, Fan sites, and the likes.
What do you mean with "check your HDD location"?
Sounds like something I'd neef

**Comment by mike111769** [comment]
OK I.looked at the image more closely , sometimes when you use all the floppy drives, say you insert locale, well they'll ALL change to.locale and screw up.

Try using a single floppy drive, and verify after you insert img, go back to the install, if it errors, check that the floppy image is the one you inserted...

I've had that issue a few times when using multi disk drives on the workbench install...

If I seen the image correctly it had already installed the 1st disk so your HDD location should be fine...

**Comment by chiaravalle** [comment]
I'm already swapping floppy imagies using only 1 floppy drive

**Comment by mike111769** [comment]
Well, if I'm correct, and it's installing the first disk then the only thing I can think of is it's the wrong img..

Verify your write location for the HDD, I've got mine set to internal, Android/data/atua.anddev.uae4arm/UAE I don't use the internal/external in the SDI settings..

OK I just verified on mine that inserting the wrong disk doesn't throw that error....

Got me stumped, I get insert correct disk..

I'm still learning towards a corrupt image, because it's finding the disk "name" it wants but not the files....

Maybe try a different disk type, 5.25 or something that guarantees you have a different image...

this is the directory of my locale disk, might want to take a look in the disk img itself..

![Screenshot_20230826-173446](https://github.com/lubomyr/uae4arm/assets/80056148/38a19a3d-5518-4be6-81b4-70127320037c)

**Comment by mike111769** [comment]
Another thing you can try, and, at least to me, it's a crappy way of doing it, but you can find a pre-installed HDD image, and just DOPUS it over to a directory HDD if you want....

The remove the HDD img and redo HD1 to HD0 And rename it to "system", the reboot....

The  .zip your system directory for sade keeping, I have like 20 backed up in .zips.

Workbench base
MUI installed
SCALOS installed

etc

And for good reason, took me DAYS to get it to this point! 

![Screenshot_20230826-175302](https://github.com/lubomyr/uae4arm/assets/80056148/dc9eeeb8-c65d-4abf-8fd5-9e040b921fee)

**Comment by chiaravalle** [comment]
> Well, if I'm correct, and it's installing the first disk then the only thing I can think of is it's the wrong img..
> 
> Verify your write location for the UAE, I've got mine set to internal, Android/data/atua.anddev.uae4arm/UAE I don't use the internal/external in the SDI settings..
> 
> OK I just verified on mine that inserting the wrong disk doesn't throw that error....
> 
> Got me stumped, I get insert correct disk..
> 
> I'm still learning towards a corrupt image, because it's finding the disk "name" it wants but not the files....,
> 
> Maybe try a different disk type, 5.25 or something that guarantees you have a different image...
> 
> this is the directory of my locale disk, might want to take a look in the disk img itself..
> 
> ![Screenshot_20230826-173446](https://user-images.githubusercontent.com/80056148/263499698-38a19a3d-5518-4be6-81b4-70127320037c.png)

Weird, my locale floppy image looks containing files, but I can't see its contents.
I tried booting with install/boot wb image in 1st floppy and locale in 2nd, then open locale in the drawer.
No file listed, but it tells there are files because there's used space.

See 
![Screenshot_20230827-041202_Uae4arm](https://github.com/lubomyr/uae4arm/assets/71562926/9c9e16ae-5ee0-442f-a5c1-ccb4d4fba638)

**Comment by chiaravalle** [comment]
P.S.: I also saw I can't browse the font disk

**Comment by chiaravalle** [comment]
> Another thing you can try, and, at least to me, it's a crappy way of doing it, but you can find a pre-installed HDD image, and just DOPUS it over to a directory HDD if you want....
> 
> The remove the HDD img and redo HD1 to HD0 And rename it to "system", the reboot....
> 
> The .zip your system directory for sade keeping, I have like 20 backed up in .zips.
> 
> Workbench base MUI installed SCALOS installed
> 
> etc
> 
> And for good reason, took me DAYS to get it to this point!
> 
> ![Screenshot_20230826-175302](https://user-images.githubusercontent.com/80056148/263500067-dc9eeeb8-c65d-4abf-8fd5-9e040b921fee.png)

I could try with Amiga Forever's installation, but not before Tuesday, because I'm not at home right now, and I have required data on my home pc' hard disk

I'll keep posted

**Comment by chiaravalle** [comment]
Or at least, can you lend me just those 2 floppy images?
In PM would be fine too.

Thanks for either

**Comment by mike111769** [comment]
Sorry can't do that, you have to 9wn a copy to use them..

Copyright laws.

**Comment by mike111769** [comment]
And actually just thought of another issue I used to have...  when you swap imgs eject the img, resume the Emulator, wait for the drive activity to stop, then go back and insert the img....

Not sure if it was WB but something gave me an issue with it not catching up to the disk emulation....

**Comment by chiaravalle** [comment]
Hello everyone again.
As I just got back home, I ripped off the WorkBench installation from my Cloanto's Amiga Forever installation directory "hard drive".
Made a copy of it and put in the Uae4Arm folder, where convenient.

Now, I just miss 2 things:
1 - I'd like the KickStart to be load when I load my configuration, now I have to do it manually every time
2 - I'd like to give the maximum amount of RAM possible to my machine, so please, anyone, share your RAM configurations

Thanks a lot for your help, especially those of you which wrote me personally, a special thank.

Regards, have a nice day =)
