### ISSUE TITLE
UAE4ARM crashing on Shield TV after latest updates

### ISSUE THREAD

**Issue by Honosuseri** [lubomyr/uae4arm#8]
Really appreciate the update to the emulator however...

The latest update (March 2018) which was installed via the google play store has broken the emulator on my Shield TV. The app is crashing on the SDL splash screen, it does work on my Android phone though. So I'm wondering if this is an Android TV related issue?

Many thanks for all your efforts

**Comment by lubomyr** [comment]
Which android version is on your ShieldTV ?

you can use with it previous beta version 1.0.0.19
https://drive.google.com/open?id=1N6lR5QWREPhXXdUdDOOa5gnMD99kDX4V

2018-03-29 20:17 GMT+03:00 Honosuseri <notifications@github.com>:

**Comment by Honosuseri** [comment]
Version 7 my friend.

Thanks for providing the link to rollback to a previous version. Was excited to test the changes out, thought I should make you aware of the issue.

**Comment by Honosuseri** [comment]
My phone notified me that UAE4ARM had been updated again. Tried once more on the STV but it's still crashing on startup. The beta version you linked above is working on the STV though.

Thanks again for all your efforts, I wish you all the best with resolving the issues

**Comment by Gazdaman** [comment]
I too have the crashing issue on Nvidea Shield TV with the latest Google Play release of UAE4ARM.
My Shield is on Android Nougat

Now using the rollback version Lubomyr provided above.

**Comment by Honosuseri** [comment]
Well my STV is now on Shield Experience 7 (Android 8/Oreo). There have been a number of updates to Uae4arm over time too.

The emulator will now launch on the STV but crashes within a few seconds. I've managed to launch games via frontends using .uae files. The games seem to fair a little better BUT do eventually crash.

Just wanted to thank lubomyr for his efforts. I do hope to see the issue resolved completely in the near future

**Comment by ransom1122** [comment]
@lubomyr

Its been 12 months with no apparent fix for uae4arm on ShieldTV?

NOTE.. All crashes occur when navigating through Uae4arm GUI.

Please could we have a fix as ShieldTVs are becoming more affordable nowdays and still a powerhouse machine for Android.

**Comment by Honosuseri** [comment]
[uae4arm.txt](https://github.com/lubomyr/uae4arm/files/3489548/uae4arm.txt)
The Shield TV is now updated to Android Pie. I've extracted the latest version of uae4arm from my phone and sideloaded to the STV, it flat out crashes when loading (I'm aware it's not officially compatible with Android TV devices). I'll provide a logcat hopefully it will help you narrow down the problem. If there is anything I can do to assist, don't hesitate to let me know.

Thanks in advance for all the effort you've put into bringing the Amiga to Android Lubomyr

**Comment by ransom1122** [comment]
Yep latest version of uae4arm. Is pigs breakfast on Android Pie for STV :/

**Comment by thatman84** [comment]
The latest version 1.0.3.0 is now working on my STV with latest android updates also. :) good news

Still some random crashes in gui.

**Comment by lubomyr** [comment]
fixed
